[programs.devnet]
myepicproject = "PaMrfGQjVkkgVsPwRs4uHUvm9RNdTWpJuyCrtX4SD8p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/lee/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
